import Head from "next/head";
import Link from "next/link";
import { getPosts } from "../utils";

export async function getStaticProps() {
  const posts = await getPosts();
  if (!posts) {
    return {
      notFound: true,
    };
  }
  return {
    props: { posts },
  };
}

export default function Home(props) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="posts-container">
        {props.posts.map((post) => (
          <div className="post-preview" key={post.id}>
            <h4>
              <Link href={`/post/${post.slug}`}>{post.title}</Link>
            </h4>
          </div>
        ))}
      </div>
    </div>
  );
}
